name: jaspr_daisyui_components
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  build_runner: ^2.4.15
  jaspr: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  # path: ^1.8.0

dev_dependencies:
  lints: any
  test: ^1.24.0
